version: "3.8"
services:
  change-vol-ownership:
    image: alpine
    user: "root"
    volumes:
      - ceph-conf:/etc/ceph
    command: chown -R 167:167 /etc/ceph
  spdk:
    image: quay.io/ceph/spdk:$SPDK_VERSION
    profiles:
      - build
    build:
      context: spdk/
      dockerfile: ../Dockerfile.spdk
      args:
        SPDK_VERSION:
        SPDK_CEPH_VERSION:
        SPDK_PKGDEP_ARGS:
        SPDK_CONFIGURE_ARGS:
        SPDK_MAKEFLAGS:
        SPDK_NAME:
        SPDK_SUMMARY:
        SPDK_DESCRIPTION:
        SPDK_URL:
        SPDK_MAINTAINER: $MAINTAINER
        BUILD_DATE:
        SPDK_GIT_REPO:
        SPDK_GIT_BRANCH:
        SPDK_GIT_COMMIT:
      labels:
        io.ceph.nvmeof:
  ceph:
    image: quay.io/ceph/vstart-cluster:$CEPH_CLUSTER_VERSION
    container_name: ceph
    build:
      context: .
      dockerfile: Dockerfile.ceph
      args:
        CEPH_CLUSTER_VERSION:
      labels:
        io.ceph.nvmeof:
    depends_on:
      change-vol-ownership:
        condition: service_completed_successfully
    environment:
      CEPH_VSTART_ARGS:
      VSTART_ARGS: --without-dashboard --memstore
      TOUCHFILE: /tmp/ceph.touch
    entrypoint: >-
      sh -c './vstart.sh --new $$VSTART_ARGS &&
      ceph osd pool create rbd &&
      sleep infinity'
    healthcheck:
      test: ceph osd pool stats rbd
      start_period: 6s
      interval: 3s
    volumes:
      - ceph-conf:/etc/ceph
    networks:
      default:
        ipv4_address: 192.168.13.2
  nvmeof-base:
    build:
      context: .
      args:
        NVMEOF_TARGET: gateway
        NVMEOF_SPDK_VERSION:
        NVMEOF_NAME:
        NVMEOF_SUMMARY:
        NVMEOF_DESCRIPTION:
        NVMEOF_URL:
        NVMEOF_VERSION:
        NVMEOF_MAINTAINER: $MAINTAINER
        NVMEOF_TAGS:
        NVMEOF_WANTS:
        NVMEOF_EXPOSE_SERVICES:
        BUILD_DATE:
        NVMEOF_GIT_REPO:
        NVMEOF_GIT_BRANCH:
        NVMEOF_GIT_COMMIT:
      labels:
        io.ceph.nvmeof:
    hostname: nvmeof
    volumes:
      # sudo bash -c 'echo 1024 > /sys/devices/system/node/node0/hugepages/hugepages-2048kB/nr_hugepages'
      # https://spdk.io/doc/containers.html
      # TODO: Pending of https://github.com/spdk/spdk/issues/2973
      - /dev/hugepages:/dev/hugepages
      - /dev/vfio/vfio:/dev/vfio/vfio
      - ceph-conf:/etc/ceph:ro
      - $NVMEOF_CONFIG:/src/ceph-nvmeof.conf
    cap_add:
      - SYS_ADMIN # huge-pages
      - CAP_SYS_NICE # RTE
      - SYS_PTRACE # gdb
    ulimits:
      nofile: $NVMEOF_NOFILE
      memlock: -1
    networks:
      default:
        ipv4_address: $NVMEOF_IP_ADDRESS
    ports:
      - "$NVMEOF_IO_PORT:$NVMEOF_IO_PORT" # I/O controllers
      - "$NVMEOF_GW_PORT:$NVMEOF_GW_PORT" # Gateway
      - "$NVMEOF_DISC_PORT:$NVMEOF_DISC_PORT" # Discovery
  nvmeof:
    extends:
      service: nvmeof-base
    image: quay.io/ceph/nvmeof:$NVMEOF_VERSION
    depends_on:
      ceph:
        condition: service_healthy
  nvmeof-builder:
    extends:
      service: nvmeof-base
    image: nvmeof-builder
    build:
      target: builder-base
    volumes:
      - .:/src
  nvmeof-devel:
    # Runs from source code in current dir
    extends:
      service: nvmeof-base
    image: quay.io/ceph/nvmeof:$NVMEOF_VERSION
    depends_on:
      ceph:
        condition: service_healthy
    volumes:
      - ./control:/src/control
  nvmeof-cli:
    image: quay.io/ceph/nvmeof-cli:$NVMEOF_VERSION
    build:
      context: .
      args:
        NVMEOF_TARGET: cli
        NVMEOF_NAME: $NVMEOF_CLI_NAME
        NVMEOF_SUMMARY: $NVMEOF_CLI_SUMMARY
        NVMEOF_DESCRIPTION: $NVMEOF_CLI_DESCRIPTION
        NVMEOF_URL:
        NVMEOF_VERSION:
        NVMEOF_MAINTAINER: $MAINTAINER
        NVMEOF_TAGS: ""
        NVMEOF_WANTS: ""
        NVMEOF_EXPOSE_SERVICES: ""
        BUILD_DATE:
        NVMEOF_GIT_REPO:
        NVMEOF_GIT_BRANCH:
        NVMEOF_GIT_COMMIT:
      labels:
        io.ceph.nvmeof:
volumes:
  ceph-conf:
networks:
  default:
    ipam:
      config:
        - subnet: 192.168.13.0/24
